### ISSUE TITLE
Replace Flipper with WebSocket from Ktor

### ISSUE THREAD

**Issue by kitakkun** [kitakkun/back-in-time-plugin#15]
## Problem

To make back-in-time-plugin available for other platforms(iOS, Desktop, and web), we need to remove Flipper from dependencies.

Though Flipper supports iOS, and allows to implement its client manually, it is not realistic to fully depend on it. Especially, to support iOS, we need to use cocoapod module. This is too hard for me.

Also, Flipper Plugin is developed by TypeScript. If we can implement debugger with Kotlin, we can share data classes representing internal events directly. This is a huge advantage.

## Tasks

- [x] implement websocket client
- [x] implement websocket server
- [ ] remove Flipper dependencies

**Comment by kitakkun** [comment]
After messing around with Kotlin/JS, I thought it is feasible enough to maintain both Flipper plugin and IntelliJ plugin.

Close this issue as not planned because I will continue to support debugging via Flipper!
