### ISSUE TITLE
Implement Debugging Tool by Compose for Desktop

### ISSUE THREAD

**Issue by kitakkun** [kitakkun/back-in-time-plugin#16]
To remove Flipper dependency, we need to implement our own debugger from scratch.

We are planning to develop debugging tool by using Compose for Desktop because it's becoming popular and growing rapidly(and just because I love compose...).

## Tasks

- [x] implement data layer using SQLDelight.
- [x] implement shared ui module which contains theme,  colors, custom views, and so on.
- [ ] implement feature module which provides each debugger feature.
- [ ] put all together and make a standalone debugger app.

**Comment by kitakkun** [comment]
module structure would be...

- backintime-debugger
  - app
  - data
  - featurecommon
  - feature
    - instance
    - log
    - server
    - settings

**Comment by kitakkun** [comment]
Now I'm actively working on compose-based debugging tool development.
However, this requires some amount of time.

The current planned implementation details:
- Architecture: similar to droidkaigi2024 conference app.
- Data management: use androidx.room for persisting data.
- UI: Compose for Desktop.
- Connection: If possible, kotlinx.rpc, if not, go with Ktor WebSocket.

**Comment by kitakkun** [comment]
I setup standalone debugger in #136(Used Compose for Desktop).
Completed.
